improved readability

diff --git a/dot-local/scripts/battery-monitor b/dot-local/scripts/battery-monitor
--- a/dot-local/scripts/battery-monitor
+++ b/dot-local/scripts/battery-monitor
@@ -28,6 +28,55 @@ function kill_prev() {
     kill $(pgrep -f $0 | grep -v $$) >/dev/null 2>&1
 }
 
+function validate_input() {
+    while :;
+    do
+        case $1 in
+            -h|-\?|--help)
+                usage
+                exit 0
+                ;;
+            -k|--kill)
+                kill_prev
+                echo "All processes killed"
+                exit 0
+                ;;
+            --min=?*)
+                min=${1#*=}
+                ;;
+            --max=?*)
+                max=${1#*=}
+                ;;
+            --quiet|-q)
+                should_notify=false
+                ;;
+            ?*)
+                echo "ERROR: $1 is in an invalid option. See usage"
+                usage
+                exit 1
+                ;;
+            *)
+                shift
+                break
+        esac
+        shift
+    done
+
+    if [[ $min -ge $max ]]; then
+        echo "ERROR: min cannot be greater than or equal to max"
+        usage
+        exit 1
+    elif [[ $min -le 0 ]]; then
+        echo "ERROR: min cannot be less than or equal to 0"
+        usage
+        exit 1
+    elif [[ $max -ge 100 ]]; then
+        echo "ERROR: max cannot be greater than or equal to 100"
+        usage
+        exit 1
+    fi
+}
+
 function notify() {
     notify-send -w --app-name="Battery Monitor" --urgency="critical" "$1" "$2" &
 }
@@ -49,78 +98,32 @@ function monitor() {
         local bat_percent=$(get_percentage)
 
         if [[ $(get_plugged) == "yes" ]]; then
-            if [[ $bat_percent -ge $2 ]]; then
-                $3 && notify "Battery reached $2%" "Unplug the power cable." >/dev/null 2>&1
+            if [[ $bat_percent -ge $max ]]; then
+                $should_notify && notify "Battery reached $max%" "Unplug the power cable." >/dev/null 2>&1
                 ~/.local/python/ty-plug/ty-plug -s off
                 while [ $(get_plugged) == "yes" ]; do :; done
-                $3 && kill -2 $!
+                $should_notify && kill -2 $!
             fi
         else
-            if [[ $bat_percent -le $1 ]]; then
-                $3 && notify "Battery is below $1%" "Plug in the power cable." >/dev/null 2>&1
+            if [[ $bat_percent -le $min ]]; then
+                $should_notify && notify "Battery is below $min%" "Plug in the power cable." >/dev/null 2>&1
                 ~/.local/python/ty-plug/ty-plug -s on
                 while [ $(get_plugged) == "no" ]; do :; done
-                $3 && kill -2 $!
+                $should_notify && kill -2 $!
             fi
         fi
     done
 }
 
-#################################################################
-#                   Main Program                                #
-#                                                               #
-#################################################################
+function main() {
+    local min=60
+    local max=70
+    local should_notify=true
 
-min=60
-max=70
-should_notify=true
-while :;
-do
-    case $1 in
-        -h|-\?|--help)
-            usage
-            exit 0
-            ;;
-        -k|--kill)
-            kill_prev
-            echo "All processes killed"
-            exit 0
-            ;;
-        --min=?*)
-            min=${1#*=}
-            ;;
-        --max=?*)
-            max=${1#*=}
-            ;;
-        --quiet|-q)
-            should_notify=false
-            ;;
-        ?*)
-            echo "ERROR: $1 is in an invalid option. See usage"
-            usage
-            exit 1
-            ;;
-        *)
-            shift
-            break
-    esac
-    shift
-done
+    validate_input $@
+    kill_prev
+    monitor & disown >/dev/null 2>&1
+}
 
-if [[ $min -ge $max ]]; then
-    echo "ERROR: min cannot be greater than or equal to max"
-    usage
-    exit 1
-elif [[ $min -le 0 ]]; then
-    echo "ERROR: min cannot be less than or equal to 0"
-    usage
-    exit 1
-elif [[ $max -ge 100 ]]; then
-    echo "ERROR: max cannot be greater than or equal to 100"
-    usage
-    exit 1
-fi
-
-kill_prev
-monitor $min $max $should_notify & disown >/dev/null 2>&1
+main $@
 
